# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fnmjl65ZDc1XjDKOAxtmUSVw9QHgGDaj
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Configuração inicial da página
st.set_page_config(page_title="Painel de Projeções", layout="wide")
st.title("Curva de Projeção vs Simulação")

# Carregamento dos dados do arquivo base.xlsx no mesmo repositório
@st.cache_data
def carregar_dados():
    try:
        df = pd.read_excel('base.xlsx')
        df['DATA_INICIAL'] = pd.to_datetime(df['DATA_INICIAL'])
        df['%MATERIAL_PAI_CHAVE'] = df['%MATERIAL_PAI_CHAVE'].astype(str)
        return df
    except FileNotFoundError:
        st.error("⚠️ Arquivo 'base.xlsx' não encontrado. Verifique se ele está na mesma pasta do app.py.")
        return pd.DataFrame()
    except Exception as e:
        st.error(f"⚠️ Erro ao carregar o arquivo: {e}")
        return pd.DataFrame()

df = carregar_dados()

# Verifica se o DataFrame foi carregado corretamente antes de renderizar a tela
if not df.empty:
    st.subheader("Filtros")

    col1, col2, col3 = st.columns(3)

    with col1:
        opcoes_dept = ['Todos'] + sorted(df['Departamento'].dropna().unique().tolist())
        dept = st.selectbox('Departamento:', opcoes_dept)

    df_temp1 = df if dept == 'Todos' else df[df['Departamento'] == dept]

    with col2:
        opcoes_sub = ['Todos'] + sorted(df_temp1['Subgrupo'].dropna().unique().tolist())
        sub = st.selectbox('Subgrupo:', opcoes_sub)

    df_temp2 = df_temp1 if sub == 'Todos' else df_temp1[df_temp1['Subgrupo'] == sub]

    with col3:
        opcoes_forma = ['Todos'] + sorted(df_temp2['FORMA_ABASTECIMENTO'].dropna().unique().tolist())
        forma = st.selectbox('Forma de Abastecimento:', opcoes_forma)

    df_temp3 = df_temp2 if forma == 'Todos' else df_temp2[df_temp2['FORMA_ABASTECIMENTO'] == forma]

    col4, col5, col6 = st.columns(3)

    with col4:
        opcoes_ciclo = ['Todos'] + sorted(df_temp3['CICLO DE VIDA'].dropna().unique().tolist())
        ciclo = st.selectbox('Ciclo de Vida:', opcoes_ciclo)

    df_temp4 = df_temp3 if ciclo == 'Todos' else df_temp3[df_temp3['CICLO DE VIDA'] == ciclo]

    with col5:
        opcoes_mat = ['Todos'] + sorted(df_temp4['%MATERIAL_PAI_CHAVE'].dropna().unique().tolist())
        material = st.selectbox('Código Material:', opcoes_mat)

    # DataFrame final filtrado
    df_filtrado = df_temp4 if material == 'Todos' else df_temp4[df_temp4['%MATERIAL_PAI_CHAVE'] == material]

    # Plotagem do Gráfico
    if df_filtrado.empty:
        st.warning("⚠️ Nenhum dado encontrado para a combinação selecionada.")
    else:
        df_agrupado = df_filtrado.groupby(['DATA_INICIAL', 'Semana Comercial'])[['QTD PROJEÇÃO', 'QTD PROJ SIM']].sum().reset_index()
        df_agrupado = df_agrupado.sort_values('DATA_INICIAL')
        df_agrupado['Semana Comercial'] = df_agrupado['Semana Comercial'].astype(int).astype(str)

        df_agrupado['DIFERENCA'] = df_agrupado['QTD PROJ SIM'] - df_agrupado['QTD PROJEÇÃO']
        diferenca_total = df_agrupado['DIFERENCA'].sum()

        fig, ax = plt.subplots(figsize=(15, 6))

        ax.plot(df_agrupado['Semana Comercial'], df_agrupado['QTD PROJEÇÃO'], marker='o', linestyle='-', color='#1f77b4', label='QTD PROJEÇÃO')
        ax.plot(df_agrupado['Semana Comercial'], df_agrupado['QTD PROJ SIM'], marker='s', linestyle='--', color='#ff7f0e', label='QTD PROJ SIM')

        ax.fill_between(df_agrupado['Semana Comercial'],
                         df_agrupado['QTD PROJEÇÃO'],
                         df_agrupado['QTD PROJ SIM'],
                         color='gray', alpha=0.2, label='Área de Diferença')

        for i in range(len(df_agrupado)):
            x_val = df_agrupado['Semana Comercial'].iloc[i]
            y_proj = df_agrupado['QTD PROJEÇÃO'].iloc[i]
            y_sim = df_agrupado['QTD PROJ SIM'].iloc[i]
            dif_val = df_agrupado['DIFERENCA'].iloc[i]

            y_mid = (y_proj + y_sim) / 2
            sinal = "+" if dif_val > 0 else ""

            ax.text(x_val, y_mid, f'{sinal}{dif_val:.0f}',
                     ha='center', va='center', fontsize=9, color='black',
                     bbox=dict(facecolor='white', alpha=0.7, edgecolor='none', boxstyle='round,pad=0.2'))

        ax.set_title(f'Diferença Total no Período: {diferenca_total:+.0f}', fontsize=14, pad=15, fontweight='bold')
        ax.set_xlabel('Semana Comercial', fontsize=11)
        ax.set_ylabel('Quantidade', fontsize=11)
        ax.legend()
        ax.grid(True, linestyle=':', alpha=0.6)

        st.pyplot(fig)